
DROP DATABASE IF EXISTS crime_report;
DROP SCHEMA IF EXISTS role CASCADE;
DROP TABLE IF EXISTS public."user" CASCADE;
DROP TABLE IF EXISTS public.crime CASCADE;
DROP TABLE IF EXISTS public.role CASCADE;
DROP TABLE IF EXISTS public.crime_case CASCADE;
ALTER TABLE public."user" DROP CONSTRAINT IF EXISTS fk_role_id CASCADE;
ALTER TABLE public.crime_case DROP CONSTRAINT IF EXISTS fk_reporter_id CASCADE;
ALTER TABLE public.crime_case DROP CONSTRAINT IF EXISTS fk_handler_id CASCADE;
ALTER TABLE public.crime_case DROP CONSTRAINT IF EXISTS fk_crime_id CASCADE;

CREATE DATABASE crime_report;
